import Head from "next/head";
import { Rubik } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const rubik = Rubik({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Next Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<style jsx global>{`
					html {
						font-family: ${rubik.style.fontFamily};
					}
				`}</style>
			</Head>
			<main className={styles.main}>
				<h1 className="text-3xl font-bold underline">Hello world!</h1>
			</main>
		</>
	);
}
