import Head from "next/head";
import { Rubik } from "@next/font/google";
import Header from "@/components/Header";
import TopCards from "@/components/TopCards";

const rubik = Rubik({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Next Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<style jsx global>{`
					html {
						font-family: ${rubik.style.fontFamily};
					}
				`}</style>
			</Head>
			<main className="bg-neutral-100 min-h-screen">
				<Header />
				<TopCards />
				<div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4"></div>
			</main>
		</>
	);
}
